// The coordinator's film (Efficiency King: "the coordinator AI's suggested
// play for him is right 10% more often (it reads his best matchups)"): how
// every everyday play in the book gains against every Beasts call, from
// the AI-vs-AI sim. Each cell is FILM_REPS snaps (the practice roster, the
// 1980s 49ers, against the all-time Beasts in the package the call brings,
// 1st and 10 from the 35, the ball on each hash and the middle, flipped and
// not), stored as the whole yards each gained (a turnover as −10). The
// coordinator reads it as the odds a play makes the yards a situation
// needs against the calls the Beasts make there (sim/coordinator.ts).
// Regenerate after a sim change that moves outcomes:
//   node tools/run-ts.mjs tools/sim/film.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { BASE_PLAYS, createPlay, DEF_CALLS, NEUTRAL, practiceRosters, runToWhistle, type SnapshotLike } from '../../src/sim/index.ts';
import { sidesFor } from '../../src/sim/outcomes.ts';
import { fnv1a } from '../../src/engine/rng/index.ts';

const FILM_REPS = 12;
const snap = JSON.parse(readFileSync('data/ratings/ratings.v1.json', 'utf8')) as SnapshotLike;
const r = practiceRosters(snap);
const film: Record<string, Record<string, number[]>> = {};
for (const play of BASE_PLAYS) {
  film[play.id] = {};
  for (const def of DEF_CALLS) {
    const ys: number[] = [];
    for (let k = 0; k < FILM_REPS; k++) {
      const sd = sidesFor(r, play, def);
      const s = createPlay({ seed: (fnv1a(`film/${play.id}/${def.id}`) + k * 6151) >>> 0, offense: sd.offense, defense: sd.defense, play, def: sd.def, los: 35, ballY: [3.08, 0, -3.08][k % 3], toGo: 10, down: 1, user: false, flip: k % 2 === 1 });
      runToWhistle(s, () => NEUTRAL);
      const res = s.result!;
      ys.push(res.offenseBall ? Math.round(res.yards) : -10);
    }
    film[play.id]![def.id] = ys;
  }
  process.stdout.write('.');
}
const body = Object.entries(film)
  .map(([id, cells]) => `  '${id}': { ${Object.entries(cells).map(([d, ys]) => `${d}: [${ys.join(', ')}]`).join(', ')} },`)
  .join('\n');
writeFileSync(
  'src/sim/film.ts',
  `// Generated by tools/sim/film.ts: do not edit. Every everyday play against
// every Beasts call, ${FILM_REPS} AI-vs-AI snaps each (the practice roster against
// the all-time Beasts, 1st and 10 from the 35): the whole yards each gained,
// a turnover as -10. The Efficiency King's coordinator reads it.
export const FILM_REPS = ${FILM_REPS};
export const FILM: Readonly<Record<string, Readonly<Record<string, readonly number[]>>>> = {
${body}
};
`,
);
console.log(`\nwrote src/sim/film.ts (${BASE_PLAYS.length} plays × ${DEF_CALLS.length} calls × ${FILM_REPS})`);
