// Legacy → typed data extractor.
//
//   node --experimental-strip-types tools/extract/extract-legacy.ts [--freeze-ids] [--check]
//
// Parses legacy/beat-the-beasts.jsx (never modified), evaluates the top-level
// pure-literal constants in isolation and writes data/legacy/*.ts. Values are
// copied verbatim: nothing is rounded, renamed or corrected here.
//
// Every PLAYERS / DEFENSE / UNITS entry gets a stable `id` and its
// `legacyIndex`. Ids are frozen in data/legacy/ids.json: the run fails if the
// regenerated ids differ from the frozen list, unless --freeze-ids is passed.
// --check writes nothing and fails if any generated file would change.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ID_DATASETS, LEGACY_PATH, makeIds, parseLegacyFile } from './parseLegacy.ts';
import type { Literal, NaturalKeyed } from './parseLegacy.ts';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const OUT_DIR = join(ROOT, 'data/legacy');
const IDS_PATH = join(OUT_DIR, 'ids.json');

const args = new Set(process.argv.slice(2));
const FREEZE = args.has('--freeze-ids');
const CHECK = args.has('--check');

// ---------------------------------------------------------------------------
// Serialization (TS source, one entry per line for readable diffs)
// ---------------------------------------------------------------------------

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const INT_KEY = /^(0|[1-9][0-9]*)$/;

function key(k: string): string {
  return IDENT.test(k) || INT_KEY.test(k) ? k : JSON.stringify(k);
}

function num(n: number): string {
  if (!Number.isFinite(n)) throw new Error(`non-finite number ${n}`);
  return Object.is(n, -0) ? '-0' : String(n);
}

/** Inline serialization of a literal. */
function lit(v: Literal): string {
  if (v === null) return 'null';
  if (typeof v === 'string') return JSON.stringify(v);
  if (typeof v === 'number') return num(v);
  if (typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) return '[' + v.map(lit).join(', ') + ']';
  const parts = Object.entries(v).map(([k, x]) => `${key(k)}: ${lit(x)}`);
  return parts.length ? '{ ' + parts.join(', ') + ' }' : '{}';
}

/** Array of entries, one per line. */
function linesArray(items: readonly Literal[]): string {
  return '[\n' + items.map((x) => '  ' + lit(x) + ',\n').join('') + ']';
}

/** Object with one member per line. */
function linesObject(obj: { [k: string]: Literal }): string {
  return '{\n' + Object.entries(obj).map(([k, x]) => `  ${key(k)}: ${lit(x)},\n`).join('') + '}';
}

// ---------------------------------------------------------------------------
// Checks on the legacy shapes (fail loudly if legacy isn't what we expect)
// ---------------------------------------------------------------------------

type Obj = { [k: string]: Literal };

function asObjArray(name: string, v: Literal | undefined): Obj[] {
  if (!Array.isArray(v)) throw new Error(`${name} is not an array`);
  return v.map((x, i) => {
    if (x === null || typeof x !== 'object' || Array.isArray(x)) throw new Error(`${name}[${i}] is not an object`);
    return x;
  });
}

function asObj(name: string, v: Literal | undefined): Obj {
  if (v === null || v === undefined || typeof v !== 'object' || Array.isArray(v)) throw new Error(`${name} is not an object`);
  return v;
}

function requireKeys(name: string, entries: Obj[], keys: string[]): void {
  entries.forEach((e, i) => {
    const got = Object.keys(e).join(',');
    if (got !== keys.join(',')) throw new Error(`${name}[${i}] keys ${got} != ${keys.join(',')}`);
    if (typeof e.n !== 'string' || typeof e.t !== 'string' || typeof e.d !== 'string') throw new Error(`${name}[${i}] bad n/t/d`);
    if (typeof e.imp !== 'number') throw new Error(`${name}[${i}] bad imp`);
    const s = e.s;
    if (s === null || typeof s !== 'object' || Array.isArray(s)) throw new Error(`${name}[${i}] bad s`);
  });
}

function natural(e: Obj): NaturalKeyed {
  return { n: e.n as string, t: e.t as string, d: e.d as string };
}

/** Entry with `id` and `legacyIndex` prepended, legacy keys after in legacy order. */
function withIds(entries: { e: Obj; legacyIndex: number }[], ids: string[]): Obj[] {
  return entries.map(({ e, legacyIndex }, i) => ({ id: ids[i] as string, legacyIndex, ...e }));
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

const parsed = parseLegacyFile();
const K = parsed.constants;
const legacyRel = relative(ROOT, LEGACY_PATH);

const header = (what: string): string =>
  `// GENERATED FILE: DO NOT EDIT.\n` +
  `// Generated by tools/extract/extract-legacy.ts from ${legacyRel}\n` +
  `// legacy SHA-256: ${parsed.sha256}\n` +
  `// ${what}\n` +
  `/* eslint-disable */\n\n`;

const line = (name: string): string => `legacy line ${parsed.lines[name] ?? '?'}`;

const players = asObjArray('PLAYERS', K.PLAYERS);
requireKeys('PLAYERS', players, ['n', 'p', 't', 'd', 's', 'imp', 'ea']);
const defense = asObjArray('DEFENSE', K.DEFENSE);
requireKeys('DEFENSE', defense, ['n', 'p', 't', 'd', 's', 'imp']);
const units = asObjArray('UNITS', K.UNITS);
requireKeys('UNITS', units, ['n', 'p', 't', 'd', 's', 'imp', 'key']);

const olUnits = units.map((e, legacyIndex) => ({ e, legacyIndex })).filter((x) => x.e.p === 'OL');
const defUnits = units.map((e, legacyIndex) => ({ e, legacyIndex })).filter((x) => x.e.p === 'DEF');
if (olUnits.length + defUnits.length !== units.length) throw new Error('UNITS has entries that are neither OL nor DEF');

const ids = {
  players: makeIds(ID_DATASETS.players, 'person', players.map(natural)),
  defense: makeIds(ID_DATASETS.defense, 'person', defense.map(natural)),
  olUnits: makeIds(ID_DATASETS.olUnits, 'unit', olUnits.map((x) => natural(x.e))),
  defUnits: makeIds(ID_DATASETS.defUnits, 'unit', defUnits.map((x) => natural(x.e))),
};
const idsJson = JSON.stringify(ids, null, 2) + '\n';

if (!FREEZE) {
  if (!existsSync(IDS_PATH)) {
    throw new Error(`${relative(ROOT, IDS_PATH)} does not exist. Run once with --freeze-ids to create it.`);
  }
  const frozen = JSON.parse(readFileSync(IDS_PATH, 'utf8')) as Record<string, string[]>;
  for (const [ds, list] of Object.entries(ids)) {
    const old = frozen[ds];
    if (!old || old.length !== list.length || old.some((id, i) => id !== list[i])) {
      const i = old ? list.findIndex((id, j) => id !== old[j]) : 0;
      throw new Error(
        `Regenerated ids for "${ds}" differ from the frozen ids.json (first difference at index ${i}: ` +
          `${old?.[i] ?? '<none>'} -> ${list[i] ?? '<none>'}). Ids must never change; ` +
          `if this is intended, re-run with --freeze-ids and review the diff.`,
      );
    }
  }
}

const P = (n: string): Literal => {
  const v = K[n];
  if (v === undefined) throw new Error(`missing ${n}`);
  return v;
};

const files: Record<string, string> = {};

files['players.ts'] =
  header(`PLAYERS (${line('PLAYERS')}): ${players.length} entries, legacy order.`) +
  `import type { Player } from './types.ts';\n\n` +
  `export const PLAYERS: readonly Player[] = ${linesArray(withIds(players.map((e, legacyIndex) => ({ e, legacyIndex })), ids.players))};\n`;

files['defense.ts'] =
  header(`DEFENSE (${line('DEFENSE')}): ${defense.length} entries, legacy order.`) +
  `import type { Defender } from './types.ts';\n\n` +
  `export const DEFENSE: readonly Defender[] = ${linesArray(withIds(defense.map((e, legacyIndex) => ({ e, legacyIndex })), ids.defense))};\n`;

files['units.ts'] =
  header(`UNITS (${line('UNITS')}) split by p: ${olUnits.length} OL + ${defUnits.length} DEF = ${units.length}. legacyIndex is the index in legacy UNITS.`) +
  `import type { DefUnit, OLUnit } from './types.ts';\n\n` +
  `/** Legacy UNITS entries with p === 'OL', in legacy order. */\n` +
  `export const OL_UNITS: readonly OLUnit[] = ${linesArray(withIds(olUnits, ids.olUnits))};\n\n` +
  `/** Legacy UNITS entries with p === 'DEF', in legacy order. */\n` +
  `export const DEF_UNITS: readonly DefUnit[] = ${linesArray(withIds(defUnits, ids.defUnits))};\n\n` +
  `/** Length of the legacy UNITS array (OL_UNITS and DEF_UNITS legacyIndex values partition 0..n-1). */\n` +
  `export const LEGACY_UNITS_LENGTH = ${units.length};\n`;

const yd = asObj('YEAR_DEFENSES', K.YEAR_DEFENSES);
files['yearDefenses.ts'] =
  header(`YEAR_DEFENSES (${line('YEAR_DEFENSES')}): ${Object.keys(yd).length} years of [team, PA/G, PF/G]. Not used by the new game.`) +
  `import type { YearDefenseRow } from './types.ts';\n\n` +
  `export const YEAR_DEFENSES: Readonly<Record<number, readonly YearDefenseRow[]>> = ${linesObject(yd)};\n`;

files['tables.ts'] =
  header(`Era and scoring tables (ERA_BASE ${line('ERA_BASE')}, DEF_ERA_BASE ${line('DEF_ERA_BASE')}, LEAGUE_AVG_PA ${line('LEAGUE_AVG_PA')}, SCORE_K ${line('SCORE_K')}, REF_ERA ${line('REF_ERA')}).`) +
  `import type { Decade, DefEraBase, EraBase, ScoreK } from './types.ts';\n\n` +
  `export const ERA_BASE: Readonly<Partial<Record<Decade, EraBase>>> = ${linesObject(asObj('ERA_BASE', K.ERA_BASE))};\n\n` +
  `export const REF_ERA: Decade = ${lit(P('REF_ERA'))};\n\n` +
  `export const DEF_ERA_BASE: Readonly<Partial<Record<Decade, DefEraBase>>> = ${linesObject(asObj('DEF_ERA_BASE', K.DEF_ERA_BASE))};\n\n` +
  `export const LEAGUE_AVG_PA: Readonly<Record<number, number>> = ${linesObject(asObj('LEAGUE_AVG_PA', K.LEAGUE_AVG_PA))};\n\n` +
  `export const SCORE_K: ScoreK = ${lit(P('SCORE_K'))};\n`;

files['constants.ts'] =
  header(`Game constants (DECADES ${line('DECADES')}, SLOT_ORDER ${line('SLOT_ORDER')}, POSITIONS ${line('POSITIONS')}, ROUNDS ${line('ROUNDS')}, NUM_DRIVES ${line('NUM_DRIVES')}, TEAM_NAME ${line('TEAM_NAME')}).`) +
  `import type { Decade, DraftPosition, Slot } from './types.ts';\n\n` +
  `export const DECADES: readonly Decade[] = ${lit(P('DECADES'))};\n` +
  `export const SLOT_ORDER: readonly Slot[] = ${lit(P('SLOT_ORDER'))};\n` +
  `export const POSITIONS: readonly DraftPosition[] = ${lit(P('POSITIONS'))};\n` +
  `export const ROUNDS: number = ${lit(P('ROUNDS'))};\n` +
  `export const NUM_DRIVES: number = ${lit(P('NUM_DRIVES'))};\n` +
  `export const TEAM_NAME: string = ${lit(P('TEAM_NAME'))};\n`;

files['palette.ts'] =
  header(`Colors and names (C ${line('C')}, POS_HEX ${line('POS_HEX')}, DECADE_HEX ${line('DECADE_HEX')}, SKIN_TONES ${line('SKIN_TONES')}, TEAM_COLORS ${line('TEAM_COLORS')}, TEAM_NICKS ${line('TEAM_NICKS')}).`) +
  `import type { DecadeHex, Palette, PosHex, SkinTone, TeamColor } from './types.ts';\n\n` +
  `export const C: Palette = ${linesObject(asObj('C', K.C))};\n\n` +
  `export const POS_HEX: Readonly<Record<string, PosHex>> = ${linesObject(asObj('POS_HEX', K.POS_HEX))};\n\n` +
  `export const DECADE_HEX: Readonly<Record<string, DecadeHex>> = ${linesObject(asObj('DECADE_HEX', K.DECADE_HEX))};\n\n` +
  `export const SKIN_TONES: readonly SkinTone[] = ${linesArray(asObjArray('SKIN_TONES', K.SKIN_TONES))};\n\n` +
  `export const TEAM_COLORS: Readonly<Record<string, TeamColor>> = ${linesObject(asObj('TEAM_COLORS', K.TEAM_COLORS))};\n\n` +
  `export const TEAM_NICKS: Readonly<Record<string, string>> = ${linesObject(asObj('TEAM_NICKS', K.TEAM_NICKS))};\n`;

files['meta.ts'] =
  header('Extraction metadata.') +
  `export const LEGACY_SHA256 = ${JSON.stringify(parsed.sha256)};\n` +
  `export const LEGACY_COUNTS = ${lit({
    PLAYERS: players.length,
    DEFENSE: defense.length,
    UNITS: units.length,
    OL_UNITS: olUnits.length,
    DEF_UNITS: defUnits.length,
    YEAR_DEFENSES: Object.keys(yd).length,
  })} as const;\n`;

files['index.ts'] =
  header('Barrel for the generated legacy data.') +
  `export * from './constants.ts';\n` +
  `export * from './defense.ts';\n` +
  `export * from './meta.ts';\n` +
  `export * from './palette.ts';\n` +
  `export * from './players.ts';\n` +
  `export * from './tables.ts';\n` +
  `export * from './units.ts';\n` +
  `export * from './yearDefenses.ts';\n` +
  `export type * from './types.ts';\n`;

if (FREEZE) files['ids.json'] = idsJson;

mkdirSync(OUT_DIR, { recursive: true });
let changed = 0;
for (const [name, text] of Object.entries(files)) {
  const path = join(OUT_DIR, name);
  const prev = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (prev === text) continue;
  changed++;
  if (CHECK) {
    console.error(`would change: ${relative(ROOT, path)}`);
    continue;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, text);
  console.log(`wrote ${relative(ROOT, path)}`);
}
if (CHECK && changed) {
  console.error(`${changed} generated file(s) out of date. Run: npm run extract`);
  process.exit(1);
}
console.log(
  `legacy ${parsed.sha256.slice(0, 12)}…  PLAYERS ${players.length}  DEFENSE ${defense.length}  ` +
    `OL_UNITS ${olUnits.length}  DEF_UNITS ${defUnits.length}  YEAR_DEFENSES ${Object.keys(yd).length}  ` +
    `(${changed ? `${changed} file(s) ${CHECK ? 'stale' : 'updated'}` : 'up to date'})`,
);
