// Regenerates docs/RATINGS_REPORT.md and docs/ratings/*.svg.
//
//   node tools/run-ts.mjs tools/ratings/report.ts
//
// BRIEF "Tools for reviewing ratings": anchor pass/fail (with the Throw
// Power before/after, the approved fixes' before/after, the consensus check
// and the diagnosis for review), era parity,
// distribution charts per attribute, top 25 per attribute and per OVR, the
// biggest movers against legacy, the traits (and docs/TRAITS.md), every
// correction applied, and every low-confidence rating among the top 200
// players by OVR.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { PHYSICAL_BY_POS, SKILL_ATTRS, attrLabel } from '../../src/engine/ratings/attributes/index.ts';
import { rateAll, type RatingRun } from '../../src/engine/ratings/engine.ts';
import { buildInputs } from '../../src/engine/ratings/inputs.ts';
import { OVR_WEIGHTS } from '../../src/engine/ratings/ovrWeights.ts';
import { TRAIT_LABELS } from '../../src/engine/ratings/traits/index.ts';
import type { RatedEntry, RatedPos } from '../../src/engine/ratings/types.ts';
import { consensusCheck, consensusSection, loadConsensus } from './consensus.ts';
import { loadSources, ROOT } from './sources.ts';
import { approvedFixesSection } from './approvedFixesReport.ts';
import { diagnosisSection } from './diagnosisReport.ts';
import { throwPowerSection } from './throwPowerReport.ts';
import { traitsDoc, traitsSection } from './traitsReport.ts';
import { byPosition, capPileups, crossStintViolations, eraParity, evaluateAnchors, legacyCorrelation, movers } from './validate.ts';

const POS_ORDER: RatedPos[] = ['QB', 'RB', 'WR', 'TE', 'OL', 'DE', 'DT', 'LB', 'CB', 'S'];
const S = loadSources();
const { inputs, notes } = buildInputs(S);
const run: RatingRun = rateAll(inputs);
const pools = byPosition(run);

const f0 = (x: number) => x.toFixed(0);
const f1 = (x: number) => x.toFixed(1);
const who = (e: RatedEntry) => `${e.name} (${e.team} ${e.decade})`;
const esc = (s: string) => s.replace(/\|/g, '\\|');
const lines: string[] = [];
const out = (...s: string[]) => lines.push(...s);

function attrKeys(pos: RatedPos): string[] {
  return [...PHYSICAL_BY_POS[pos], ...SKILL_ATTRS[pos].map((d) => d.key)];
}

// ------------------------------------------------------------------ header

const confCount = (pred: (e: RatedEntry) => boolean) => run.entries.filter(pred).length;
out(
  '# Ratings report (M2)',
  '',
  '_Generated by `node tools/run-ts.mjs tools/ratings/report.ts`. Do not edit by hand._',
  '',
  `Rated entries: **${run.entries.length}** (${POS_ORDER.map((p) => `${p} ${pools.get(p)?.length ?? 0}`).join(', ')}). OL units are split into five linemen each.`,
  `Excluded by corrections: ${S.excluded.size}. Corrections applied: ${S.applied.length}.`,
  `OVR confidence: high ${confCount((e) => e.ovr.conf === 'high')}, medium ${confCount((e) => e.ovr.conf === 'medium')}, low ${confCount((e) => e.ovr.conf === 'low')}.`,
  S.missing.length ? `\n> **Missing inputs** (these regress to priors): ${S.missing.join(', ')}` : '',
  '',
  '## How ratings are built',
  '',
  '- **Signals.** Every stat is compared to the league average over the seasons the player actually played (`data/era_baselines.json`, weighted by his games per season), as a log ratio (rates, volumes) or a difference (completion %, passer rating). Honors count per season in the stint (AP First-Team 1.0, Second-Team 0.5, Pro Bowl 0.35, MVP 1.2, OPOY/DPOY 0.8); the signal is half the stint average and half the average of its best three seasons, so a rookie year or an injury season doesn\'t bury a peak.',
  '- **Samples.** Each signal becomes a z-score within the position pool (all decades together; the signals are already era-relative) and is shrunk toward 0 by n / (n + k). n is games for per-game stats and plays for rate stats (attempts / 30, carries / 15, targets / 7, receptions / 4), so a backup\'s 150 attempts don\'t make an elite decision-maker. A verified slice covering under 40% of a stint (for example only the 1999 season of a 1990s stint) doesn\'t speak for the whole stint.',
  '- **Attributes.** Each skill attribute is a weighted sum of signals (`src/engine/ratings/attributes/*.ts`, one declarative formula per attribute). Missing evidence contributes 0 (the position average) and moves part of its weight to the player\'s other evidence (stats, honors; never body or reputation), so data-poor eras aren\'t dragged to the middle. The sum is standardized, rescaled for pool size, blended with the player\'s rank in the pool (60% rank-based normal score, 40% distance from the mean; skewed honors would otherwise pile players up at 99), and mapped through one curve: median 72, top 25% → 80+, top 5% → 90+, the expected best of the pool → 98.',
  '- **Reputation cap.** Legacy `imp`, and the legacy hand-set TE block grade, are each at most 20% of an attribute\'s formula weight and, for every player, at most 20% of the attribute\'s movement: each can amplify what the evidence says by a quarter at most, and can\'t move an attribute on its own (tested for every player and attribute).',
  '- **Occasional skills** (a linebacker\'s pass rush, a back\'s catching) have a position average below 72 and their own ceiling for the best at that position, so the best pass-rushing linebacker rates with the elite ends while the best cover linebacker stays below the elite corners.',
  '- **Pool calibration.** The defensive pools are the curated Beasts candidates: about 90% have honors, a median of 0.5–0.75 per season. The offensive pools show what rating that honors level earns (median OVR by honors band), so those pools are re-centered on it while the best stays at the top. It shows as its own line in every contribution breakdown.',
  '- **Physical attributes** are absolute (they feed physics): measured combine data first (40, bench, vertical, broad, cone, shuttle), with partial hand-timing corrections for older and pro-day times, else a position prior adjusted by body (weight relative to the era, translated to the modern game) and production signatures, flagged `estimated`. They are computed once per person and aged per stint with a position-specific curve (`src/engine/ratings/physical.ts`).',
  '- **OVR** is a weighted blend of the position\'s attributes (`src/engine/ratings/ovrWeights.ts`), standardized within the position, mapped through the same curve and calibrated the same way. For WR and TE, raw physical attributes (directly or through the skills that read them) carry at most 8% of OVR (user-approved cap, see "Approved fixes").',
  '- **Confidence** is the weight-averaged provenance of the inputs: verified 1.0, reference 0.9, legacy 0.55, estimated 0.4, prior 0. High ≥ 0.7, medium ≥ 0.4.',
  '- **99** is kept for true outliers (no pileups), so an anchor band of 99 passes at ≥ 98.5 or at rank 1–3 in the position pool.',
  '',
);

// ------------------------------------------------------------------ anchors

const anchors = evaluateAnchors(run);
const nPass = anchors.filter((a) => a.pass).length;
const nApproved = anchors.filter((a) => a.anchor.approved).length;
out(
  '## Anchor tests',
  '',
  `**${nPass} of ${anchors.length} anchors pass.** Each check shows the value and the band. Flags are anchors I think are wrong or can't be met honestly by the data; they are listed for your review rather than bent into the formulas. ${nApproved} anchors carry a band you approved changing in the ratings follow-up (marked "new band"; the old band and the reason are listed below).`,
  '',
);
out('| Anchor | Result | Checks |', '|---|---|---|');
for (const a of anchors) {
  const tag = a.anchor.approved ? ' (new band)' : '';
  out(`| ${a.label} | ${a.pass ? 'PASS' : a.anchor.review ? '**FLAG**' : 'FAIL'}${tag} | ${a.results.map((r) => `${r.pass ? '✓' : '✗'} ${esc(r.text)}`).join('<br>')} |`);
}
const changed = anchors.filter((a) => a.anchor.approved);
if (changed.length) {
  out('', '### Band changes (user-approved)', '');
  for (const a of changed) out(`- **${a.label}** (${a.pass ? 'passes' : '**still flagged**'}): ${a.anchor.approved}`);
}
const flagged = anchors.filter((a) => a.anchor.review);
if (flagged.length) {
  out('', '### Flagged anchors', '');
  for (const a of flagged) out(`- **${a.label}**${a.pass ? '' : ' (fails)'}: ${a.anchor.review}`);
}
out('');

out(...throwPowerSection(run));
out(...approvedFixesSection(run));

// ------------------------------------------------------------------ consensus

// Reads the finished run only; never changes a rating (tools/ratings/consensus.ts).
const consensus = loadConsensus();
out(...consensusSection(consensusCheck(run, consensus), consensus));
out(...diagnosisSection(run));

// ------------------------------------------------------------------ parity

const parity = eraParity(run);
out('## Era parity', '', 'Average OVR of the top N per position in each decade, minus the all-decade average of those top-Ns. N is 10 where every decade has 20+ players; the defensive pools hold 5–15 players per decade, so N is half the smallest decade there (column N). Decades with fewer than 6 players are skipped. Flag: more than 3 points off.', '');
const decs = ['1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];
out(`| Pos | N | All | ${decs.join(' | ')} |`, `|---|---|---|${decs.map(() => '---').join('|')}|`);
for (const p of POS_ORDER) {
  const r = parity.find((x) => x.pos === p);
  if (!r) continue;
  out(`| ${p} | ${r.topN} | ${f1(r.overall)} | ${decs.map((d) => (r.decades[d] ? `${r.flagged.includes(d) ? '**' : ''}${r.decades[d]!.delta >= 0 ? '+' : ''}${f1(r.decades[d]!.delta)}${r.flagged.includes(d) ? '**' : ''}` : '–')).join(' | ')} |`);
}
out('');

// ------------------------------------------------------------------ legacy comparison

const corr = legacyCorrelation(run);
const mv = movers(run);
out(
  '## Legacy comparison',
  '',
  `Spearman correlation of new OVR with legacy \`imp\` (within-position percentiles): **${corr.overall.toFixed(3)}** (target 0.75–0.9). By position: ${POS_ORDER.filter((p) => corr.byPos[p] !== undefined).map((p) => `${p} ${corr.byPos[p]!.toFixed(2)}`).join(', ')}.`,
  '',
  'Movers compare the percentile of OVR with the percentile of `imp` inside the position. The reason lists the inputs that moved OVR most (weighted through the OVR blend).',
  '',
);
for (const [title, list] of [
  ['Top 50 risers', mv.up],
  ['Top 50 fallers', mv.down],
] as const) {
  out(`<details><summary>${title}</summary>`, '', '| Player | Pos | imp (pct) | OVR (pct) | Why |', '|---|---|---|---|---|');
  for (const m of list) out(`| ${who(m.entry)} | ${m.entry.pos} | ${m.entry.imp} (${f0(m.impPct)}) | ${f0(m.entry.ovr.value)} (${f0(m.ovrPct)}) | ${esc(m.reason)} |`);
  out('', '</details>', '');
}

// ------------------------------------------------------------------ distributions

mkdirSync(ROOT + 'docs/ratings', { recursive: true });
function histSvg(pos: RatedPos, keys: string[]): string {
  const cols = 4;
  const w = 180;
  const h = 90;
  const rows = Math.ceil((keys.length + 1) / cols);
  const parts: string[] = [];
  const all = ['ovr', ...keys];
  all.forEach((k, i) => {
    const x0 = (i % cols) * (w + 16) + 8;
    const y0 = Math.floor(i / cols) * (h + 34) + 8;
    const vals = pools.get(pos)!.map((e) => (k === 'ovr' ? e.ovr.value : e.attrs[k]?.value)).filter((v): v is number => v !== undefined);
    const bins = new Array(40).fill(0) as number[];
    for (const v of vals) bins[Math.min(39, Math.max(0, Math.floor((v - 20) / 2)))]!++;
    const max = Math.max(1, ...bins);
    parts.push(`<text x="${x0}" y="${y0 + 12}" font-size="11" font-family="sans-serif" fill="#222">${k === 'ovr' ? 'OVR' : attrLabel(pos, k)}</text>`);
    bins.forEach((b, j) => {
      const bh = (b / max) * (h - 20);
      const color = j >= 35 ? '#c0392b' : j >= 30 ? '#e67e22' : '#2f6f8f';
      parts.push(`<rect x="${x0 + (j * w) / 40}" y="${y0 + h - bh}" width="${w / 40 - 0.6}" height="${bh}" fill="${color}"/>`);
    });
    parts.push(`<line x1="${x0}" y1="${y0 + h}" x2="${x0 + w}" y2="${y0 + h}" stroke="#999" stroke-width="0.5"/>`);
    for (const t of [20, 50, 70, 90, 99]) parts.push(`<text x="${x0 + ((t - 20) / 80) * w}" y="${y0 + h + 11}" font-size="8" font-family="sans-serif" fill="#666" text-anchor="middle">${t}</text>`);
  });
  const W = cols * (w + 16) + 8;
  const H = rows * (h + 34) + 8;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/>${parts.join('')}</svg>\n`;
}
out('## Distributions', '', 'Histograms of every attribute per position (2-point bins from 20 to 99; orange 80–89, red 90+).', '');
for (const p of POS_ORDER) {
  if (!pools.get(p)) continue;
  writeFileSync(ROOT + `docs/ratings/dist-${p}.svg`, histSvg(p, attrKeys(p)));
  out(`<details><summary>${p}</summary>`, '', `![${p} distributions](ratings/dist-${p}.svg)`, '', '</details>', '');
}
const pile = capPileups(run).filter((r) => r.at99 > 5);
out('### Cap pileups', '', pile.length ? `Attributes with more than 5 players at 99: ${pile.map((r) => `${r.pos} ${r.attr} (${r.at99})`).join(', ')}.` : 'No attribute has more than 5 players at 99.', '');

// ------------------------------------------------------------------ top lists

out('## Top 25 by OVR', '');
for (const p of POS_ORDER) {
  const list = [...(pools.get(p) ?? [])].sort((a, b) => b.ovr.value - a.ovr.value).slice(0, 25);
  const card = Object.entries(OVR_WEIGHTS[p]).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([k]) => k);
  out(`<details><summary>${p}</summary>`, '', `| # | Player | OVR | Conf | ${card.map((k) => attrLabel(p, k)).join(' | ')} | Traits |`, `|---|---|---|---|${card.map(() => '---').join('|')}|---|`);
  list.forEach((e, i) => out(`| ${i + 1} | ${who(e)} | ${f0(e.ovr.value)} | ${e.ovr.conf} | ${card.map((k) => f0(e.attrs[k]?.value ?? 0)).join(' | ')} | ${e.traits.map((t) => TRAIT_LABELS[t.id]).join(', ')} |`));
  out('', '</details>', '');
}
out('## Top 25 per attribute', '');
for (const p of POS_ORDER) {
  const list = pools.get(p) ?? [];
  out(`<details><summary>${p}</summary>`, '');
  for (const k of attrKeys(p)) {
    const top = [...list].filter((e) => e.attrs[k]).sort((a, b) => b.attrs[k]!.value - a.attrs[k]!.value).slice(0, 25);
    out('', `**${attrLabel(p, k)}**: ${top.map((e) => `${e.name} ${e.team} ${e.decade.slice(2)} ${f0(e.attrs[k]!.value)}${e.attrs[k]!.conf === 'low' ? '*' : ''}`).join(' · ')}`);
  }
  out('', '_* low confidence_', '', '</details>', '');
}

// ------------------------------------------------------------------ traits

out(...traitsSection(run));
writeFileSync(ROOT + 'docs/TRAITS.md', traitsDoc());

// ------------------------------------------------------------------ corrections

out('## Corrections applied', '', `From \`data/corrections.json\` (${S.applied.length}). The loader refuses any correction whose \`old\` value doesn't match legacy.`, '');
out('| Entry | Op | Field | Old → New | Reason | Source | Conf |', '|---|---|---|---|---|---|---|');
for (const c of S.applied) out(`| ${c.name} \`${c.id}\` | ${c.op} | ${c.field ?? ''} | ${c.op === 'exclude' ? '' : `${JSON.stringify(c.old)} → ${c.op === 'delete' ? '(removed)' : JSON.stringify(c.new)}`} | ${esc(c.reason)} | ${esc(c.source)} | ${c.conf} |`);
out('');

// ------------------------------------------------------------------ low confidence

const top200 = [...run.entries].sort((a, b) => b.ovr.value - a.ovr.value).slice(0, 200);
const lowConf = top200.filter((e) => e.ovr.conf === 'low' || Object.values(e.attrs).some((a) => a.conf === 'low'));
out('## Low-confidence ratings among the top 200 by OVR', '', `${lowConf.length} of the top 200 have at least one low-confidence rating.`, '');
out('| Player | Pos | OVR (conf) | Low-confidence attributes |', '|---|---|---|---|');
for (const e of lowConf) {
  const lows = Object.entries(e.attrs).filter(([, a]) => a.conf === 'low').map(([k, a]) => `${attrLabel(e.pos, k)} ${f0(a.value)}`);
  out(`| ${who(e)} | ${e.pos} | ${f0(e.ovr.value)} (${e.ovr.conf}) | ${lows.join(', ')} |`);
}
out('');

// ------------------------------------------------------------------ adapter

{
  const fitFile = JSON.parse(readFileSync(ROOT + 'data/ratings/adapter.v1.json', 'utf8')) as Record<string, Record<string, { r2?: number; w: Record<string, number> }> | number>;
  out('## Legacy-sim adapter (fitted, not tuned)', '', 'The legacy sim reads its own ability fields. `src/engine/legacy/adapter.ts` computes each one as a linear blend of new attributes, fitted by least squares to legacy\'s own values over the pool (`data/ratings/adapter.v1.json`). Legacy\'s fields lean on `imp`, which the new ratings deliberately do not reproduce, so the fit is loose by design. Calibration to the brief\'s targets (~21 / ~36 / ~14 points per game and the win-rate bands) waits for your sign-off on the ratings.', '');
  out('| Group | Field | Inputs (weights) | R² |', '|---|---|---|---|');
  for (const [g, fields] of Object.entries(fitFile)) {
    if (typeof fields === 'number') continue;
    for (const [f, v] of Object.entries(fields)) out(`| ${g} | ${f} | ${Object.entries(v.w).map(([k, w]) => `${k} ${w.toFixed(3)}`).join(', ')} | ${v.r2 ?? ''} |`);
  }
  try {
    out('', readFileSync(ROOT + 'data/ratings/adapter.v1.check.txt', 'utf8').trim(), '');
  } catch {
    out('');
  }
}

// ------------------------------------------------------------------ checks

const cross = crossStintViolations(run);
out('## Other checks', '', `- Cross-stint consistency: ${cross.length ? `${cross.length} violations (first: ${cross.slice(0, 3).join('; ')})` : 'every multi-stint player\'s physicals differ only by the aging curve.'}`);
out(`- Input assembly notes: ${notes.length} (${notes.slice(0, 5).join('; ')}${notes.length > 5 ? '; …' : ''}).`, '');

writeFileSync(ROOT + 'docs/RATINGS_REPORT.md', lines.join('\n') + '\n');
console.log(`wrote docs/RATINGS_REPORT.md (${nPass}/${anchors.length} anchors pass, spearman ${corr.overall.toFixed(3)})`);
