// Regenerates docs/RATINGS_REPORT.md and docs/ratings/*.svg.
//
//   node tools/run-ts.mjs tools/ratings/report.ts
//
// BRIEF "Tools for reviewing ratings": anchor pass/fail, era parity,
// distribution charts per attribute, top 25 per attribute and per OVR, the
// biggest movers against legacy, every correction applied, and every
// low-confidence rating among the top 200 players by OVR.

import { mkdirSync, writeFileSync } from 'node:fs';
import { PHYSICAL_BY_POS, SKILL_ATTRS, attrLabel } from '../../src/engine/ratings/attributes/index.ts';
import { rateAll, type RatingRun } from '../../src/engine/ratings/engine.ts';
import { buildInputs } from '../../src/engine/ratings/inputs.ts';
import { OVR_WEIGHTS } from '../../src/engine/ratings/ovrWeights.ts';
import { TRAIT_LABELS } from '../../src/engine/ratings/traits.ts';
import type { RatedEntry, RatedPos } from '../../src/engine/ratings/types.ts';
import { loadSources, ROOT } from './sources.ts';
import { byPosition, capPileups, crossStintViolations, eraParity, evaluateAnchors, legacyCorrelation, movers } from './validate.ts';

const POS_ORDER: RatedPos[] = ['QB', 'RB', 'WR', 'TE', 'OL', 'DE', 'DT', 'LB', 'CB', 'S'];
const S = loadSources();
const { inputs, notes } = buildInputs(S);
const run: RatingRun = rateAll(inputs);
const pools = byPosition(run);

const f0 = (x: number) => x.toFixed(0);
const f1 = (x: number) => x.toFixed(1);
const who = (e: RatedEntry) => `${e.name} (${e.team} ${e.decade})`;
const esc = (s: string) => s.replace(/\|/g, '\\|');
const lines: string[] = [];
const out = (...s: string[]) => lines.push(...s);

function attrKeys(pos: RatedPos): string[] {
  return [...PHYSICAL_BY_POS[pos], ...SKILL_ATTRS[pos].map((d) => d.key)];
}

// ------------------------------------------------------------------ header

const confCount = (pred: (e: RatedEntry) => boolean) => run.entries.filter(pred).length;
out(
  '# Ratings report (M2)',
  '',
  '_Generated by `node tools/run-ts.mjs tools/ratings/report.ts`. Do not edit by hand._',
  '',
  `Rated entries: **${run.entries.length}** (${POS_ORDER.map((p) => `${p} ${pools.get(p)?.length ?? 0}`).join(', ')}). OL units are split into five linemen each.`,
  `Excluded by corrections: ${S.excluded.size}. Corrections applied: ${S.applied.length}.`,
  `OVR confidence: high ${confCount((e) => e.ovr.conf === 'high')}, medium ${confCount((e) => e.ovr.conf === 'medium')}, low ${confCount((e) => e.ovr.conf === 'low')}.`,
  S.missing.length ? `\n> **Missing inputs** (these regress to priors): ${S.missing.join(', ')}` : '',
  '',
  '## How ratings are built',
  '',
  '- **Signals.** Every stat is compared to the league average over the seasons the player actually played (`data/era_baselines.json`), as a log ratio (rates, volumes) or a difference (completion %, passer rating). Honors are counted per season in the stint (AP First-Team 1.0, Second-Team 0.5, Pro Bowl 0.35, MVP 1.2, OPOY/DPOY 0.8).',
  '- **Standardize and shrink.** Each signal becomes a z-score within the position pool (all decades together, because the signals are already era-relative) and is shrunk toward 0 by games / (games + k), with k set per signal (noisy stats get a larger k).',
  '- **Attributes.** Each skill attribute is a weighted sum of signals (weights in `src/engine/ratings/attributes/*.ts`, one formula per attribute). The legacy reputation score `imp` is capped at 20% of the weight and is never added on top. The sum is standardized by its pool spread, rescaled for pool size, and mapped through one curve: top 5% → 90+, top 25% → 80+, median 72, the expected best of the pool → about 98. Missing inputs contribute 0 (position average) and lower the confidence.',
  '- **Physical attributes** are absolute: measured combine data first (40, bench, vertical, broad, cone, shuttle), else a position prior adjusted by body (weight relative to the era, translated to the modern game) and production signatures, flagged `estimated`. They are computed once per person and aged per stint (`src/engine/ratings/physical.ts`).',
  '- **OVR** is a weighted blend of the position\'s attributes (`src/engine/ratings/ovrWeights.ts`), standardized within the position and mapped through the same curve.',
  '- **Confidence** is the weight-averaged provenance of the inputs: verified 1.0, reference 0.9, legacy 0.55, estimated 0.4, prior 0. High ≥ 0.7, medium ≥ 0.4.',
  '',
);

// ------------------------------------------------------------------ anchors

const anchors = evaluateAnchors(run);
const nPass = anchors.filter((a) => a.pass).length;
out('## Anchor tests', '', `**${nPass} of ${anchors.length} anchors pass.** Each check shows the value and the band. Flags are anchors I think are wrong or can't be met honestly by the data; they are listed for your review rather than bent into the formulas.`, '');
out('| Anchor | Result | Checks |', '|---|---|---|');
for (const a of anchors) {
  out(`| ${a.label} | ${a.pass ? 'PASS' : a.anchor.review ? '**FLAG**' : 'FAIL'} | ${a.results.map((r) => `${r.pass ? '✓' : '✗'} ${esc(r.text)}`).join('<br>')} |`);
}
const flagged = anchors.filter((a) => a.anchor.review);
if (flagged.length) {
  out('', '### Flagged anchors', '');
  for (const a of flagged) out(`- **${a.label}**: ${a.anchor.review}`);
}
out('');

// ------------------------------------------------------------------ parity

const parity = eraParity(run);
out('## Era parity', '', 'Average OVR of the top N per position in each decade, minus the all-decade average of those top-Ns. N is 10 where every decade has 20+ players; the defensive pools hold 5–15 players per decade, so N is half the smallest decade there (column N). Decades with fewer than 6 players are skipped. Flag: more than 3 points off.', '');
const decs = ['1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s'];
out(`| Pos | N | All | ${decs.join(' | ')} |`, `|---|---|---|${decs.map(() => '---').join('|')}|`);
for (const p of POS_ORDER) {
  const r = parity.find((x) => x.pos === p);
  if (!r) continue;
  out(`| ${p} | ${r.topN} | ${f1(r.overall)} | ${decs.map((d) => (r.decades[d] ? `${r.flagged.includes(d) ? '**' : ''}${r.decades[d]!.delta >= 0 ? '+' : ''}${f1(r.decades[d]!.delta)}${r.flagged.includes(d) ? '**' : ''}` : '–')).join(' | ')} |`);
}
out('');

// ------------------------------------------------------------------ legacy comparison

const corr = legacyCorrelation(run);
const mv = movers(run);
out(
  '## Legacy comparison',
  '',
  `Spearman correlation of new OVR with legacy \`imp\` (within-position percentiles): **${corr.overall.toFixed(3)}** (target 0.75–0.9). By position: ${POS_ORDER.filter((p) => corr.byPos[p] !== undefined).map((p) => `${p} ${corr.byPos[p]!.toFixed(2)}`).join(', ')}.`,
  '',
  'Movers compare the percentile of OVR with the percentile of `imp` inside the position. The reason lists the inputs that moved OVR most (weighted through the OVR blend).',
  '',
);
for (const [title, list] of [
  ['Top 50 risers', mv.up],
  ['Top 50 fallers', mv.down],
] as const) {
  out(`<details><summary>${title}</summary>`, '', '| Player | Pos | imp (pct) | OVR (pct) | Why |', '|---|---|---|---|---|');
  for (const m of list) out(`| ${who(m.entry)} | ${m.entry.pos} | ${m.entry.imp} (${f0(m.impPct)}) | ${f0(m.entry.ovr.value)} (${f0(m.ovrPct)}) | ${esc(m.reason)} |`);
  out('', '</details>', '');
}

// ------------------------------------------------------------------ distributions

mkdirSync(ROOT + 'docs/ratings', { recursive: true });
function histSvg(pos: RatedPos, keys: string[]): string {
  const cols = 4;
  const w = 180;
  const h = 90;
  const rows = Math.ceil((keys.length + 1) / cols);
  const parts: string[] = [];
  const all = ['ovr', ...keys];
  all.forEach((k, i) => {
    const x0 = (i % cols) * (w + 16) + 8;
    const y0 = Math.floor(i / cols) * (h + 34) + 8;
    const vals = pools.get(pos)!.map((e) => (k === 'ovr' ? e.ovr.value : e.attrs[k]?.value)).filter((v): v is number => v !== undefined);
    const bins = new Array(40).fill(0) as number[];
    for (const v of vals) bins[Math.min(39, Math.max(0, Math.floor((v - 20) / 2)))]!++;
    const max = Math.max(1, ...bins);
    parts.push(`<text x="${x0}" y="${y0 + 12}" font-size="11" font-family="sans-serif" fill="#222">${k === 'ovr' ? 'OVR' : attrLabel(pos, k)}</text>`);
    bins.forEach((b, j) => {
      const bh = (b / max) * (h - 20);
      const color = j >= 35 ? '#c0392b' : j >= 30 ? '#e67e22' : '#2f6f8f';
      parts.push(`<rect x="${x0 + (j * w) / 40}" y="${y0 + h - bh}" width="${w / 40 - 0.6}" height="${bh}" fill="${color}"/>`);
    });
    parts.push(`<line x1="${x0}" y1="${y0 + h}" x2="${x0 + w}" y2="${y0 + h}" stroke="#999" stroke-width="0.5"/>`);
    for (const t of [20, 50, 70, 90, 99]) parts.push(`<text x="${x0 + ((t - 20) / 80) * w}" y="${y0 + h + 11}" font-size="8" font-family="sans-serif" fill="#666" text-anchor="middle">${t}</text>`);
  });
  const W = cols * (w + 16) + 8;
  const H = rows * (h + 34) + 8;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}"><rect width="100%" height="100%" fill="#fff"/>${parts.join('')}</svg>\n`;
}
out('## Distributions', '', 'Histograms of every attribute per position (2-point bins from 20 to 99; orange 80–89, red 90+).', '');
for (const p of POS_ORDER) {
  if (!pools.get(p)) continue;
  writeFileSync(ROOT + `docs/ratings/dist-${p}.svg`, histSvg(p, attrKeys(p)));
  out(`<details><summary>${p}</summary>`, '', `![${p} distributions](ratings/dist-${p}.svg)`, '', '</details>', '');
}
const pile = capPileups(run).filter((r) => r.at99 > 5);
out('### Cap pileups', '', pile.length ? `Attributes with more than 5 players at 99: ${pile.map((r) => `${r.pos} ${r.attr} (${r.at99})`).join(', ')}.` : 'No attribute has more than 5 players at 99.', '');

// ------------------------------------------------------------------ top lists

out('## Top 25 by OVR', '');
for (const p of POS_ORDER) {
  const list = [...(pools.get(p) ?? [])].sort((a, b) => b.ovr.value - a.ovr.value).slice(0, 25);
  const card = Object.entries(OVR_WEIGHTS[p]).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([k]) => k);
  out(`<details><summary>${p}</summary>`, '', `| # | Player | OVR | Conf | ${card.map((k) => attrLabel(p, k)).join(' | ')} | Traits |`, `|---|---|---|---|${card.map(() => '---').join('|')}|---|`);
  list.forEach((e, i) => out(`| ${i + 1} | ${who(e)} | ${f0(e.ovr.value)} | ${e.ovr.conf} | ${card.map((k) => f0(e.attrs[k]?.value ?? 0)).join(' | ')} | ${e.traits.map((t) => TRAIT_LABELS[t.id]).join(', ')} |`));
  out('', '</details>', '');
}
out('## Top 25 per attribute', '');
for (const p of POS_ORDER) {
  const list = pools.get(p) ?? [];
  out(`<details><summary>${p}</summary>`, '');
  for (const k of attrKeys(p)) {
    const top = [...list].filter((e) => e.attrs[k]).sort((a, b) => b.attrs[k]!.value - a.attrs[k]!.value).slice(0, 25);
    out('', `**${attrLabel(p, k)}**: ${top.map((e) => `${e.name} ${e.team} ${e.decade.slice(2)} ${f0(e.attrs[k]!.value)}${e.attrs[k]!.conf === 'low' ? '*' : ''}`).join(' · ')}`);
  }
  out('', '_* low confidence_', '', '</details>', '');
}

// ------------------------------------------------------------------ corrections

out('## Corrections applied', '', `From \`data/corrections.json\` (${S.applied.length}). The loader refuses any correction whose \`old\` value doesn't match legacy.`, '');
out('| Entry | Op | Field | Old → New | Reason | Source | Conf |', '|---|---|---|---|---|---|---|');
for (const c of S.applied) out(`| ${c.name} \`${c.id}\` | ${c.op} | ${c.field ?? ''} | ${c.op === 'exclude' ? '' : `${JSON.stringify(c.old)} → ${c.op === 'delete' ? '(removed)' : JSON.stringify(c.new)}`} | ${esc(c.reason)} | ${esc(c.source)} | ${c.conf} |`);
out('');

// ------------------------------------------------------------------ low confidence

const top200 = [...run.entries].sort((a, b) => b.ovr.value - a.ovr.value).slice(0, 200);
const lowConf = top200.filter((e) => e.ovr.conf === 'low' || Object.values(e.attrs).some((a) => a.conf === 'low'));
out('## Low-confidence ratings among the top 200 by OVR', '', `${lowConf.length} of the top 200 have at least one low-confidence rating.`, '');
out('| Player | Pos | OVR (conf) | Low-confidence attributes |', '|---|---|---|---|');
for (const e of lowConf) {
  const lows = Object.entries(e.attrs).filter(([, a]) => a.conf === 'low').map(([k, a]) => `${attrLabel(e.pos, k)} ${f0(a.value)}`);
  out(`| ${who(e)} | ${e.pos} | ${f0(e.ovr.value)} (${e.ovr.conf}) | ${lows.join(', ')} |`);
}
out('');

// ------------------------------------------------------------------ checks

const cross = crossStintViolations(run);
out('## Other checks', '', `- Cross-stint consistency: ${cross.length ? `${cross.length} violations (first: ${cross.slice(0, 3).join('; ')})` : 'every multi-stint player\'s physicals differ only by the aging curve.'}`);
out(`- Input assembly notes: ${notes.length} (${notes.slice(0, 5).join('; ')}${notes.length > 5 ? '; …' : ''}).`, '');

writeFileSync(ROOT + 'docs/RATINGS_REPORT.md', lines.join('\n') + '\n');
console.log(`wrote docs/RATINGS_REPORT.md (${nPass}/${anchors.length} anchors pass, spearman ${corr.overall.toFixed(3)})`);
