// GENERATED FILE: DO NOT EDIT.
// Generated by tools/extract/extract-legacy.ts from legacy/beat-the-beasts.jsx
// legacy SHA-256: 94288df62b61768af23eb8be7ad90a86deb6b99ca0a8b234be63b655e827f383
// Game constants (DECADES legacy line 7, SLOT_ORDER legacy line 157, POSITIONS legacy line 158, ROUNDS legacy line 159, NUM_DRIVES legacy line 4960, TEAM_NAME legacy line 9).
/* eslint-disable */

import type { Decade, DraftPosition, Slot } from './types.ts';

export const DECADES: readonly Decade[] = ["1960s", "1970s", "1980s", "1990s", "2000s", "2010s", "2020s"];
export const SLOT_ORDER: readonly Slot[] = ["QB", "RB", "RB2", "WR1", "WR2", "WR3", "TE", "TE2", "OL"];
export const POSITIONS: readonly DraftPosition[] = ["QB", "RB", "WR", "TE", "OL"];
export const ROUNDS: number = 9;
export const NUM_DRIVES: number = 10;
export const TEAM_NAME: string = "The Contenders";
