// GENERATED FILE: DO NOT EDIT.
// Generated by tools/extract/extract-legacy.ts from legacy/beat-the-beasts.jsx
// legacy SHA-256: 94288df62b61768af23eb8be7ad90a86deb6b99ca0a8b234be63b655e827f383
// Barrel for the generated legacy data.
/* eslint-disable */

export * from './constants.ts';
export * from './defense.ts';
export * from './meta.ts';
export * from './palette.ts';
export * from './players.ts';
export * from './tables.ts';
export * from './units.ts';
export * from './yearDefenses.ts';
export type * from './types.ts';
