// GENERATED FILE: DO NOT EDIT.
// Generated by tools/extract/extract-legacy.ts from legacy/beat-the-beasts.jsx
// legacy SHA-256: 94288df62b61768af23eb8be7ad90a86deb6b99ca0a8b234be63b655e827f383
// Extraction metadata.
/* eslint-disable */

export const LEGACY_SHA256 = "94288df62b61768af23eb8be7ad90a86deb6b99ca0a8b234be63b655e827f383";
export const LEGACY_COUNTS = { PLAYERS: 3064, DEFENSE: 386, UNITS: 255, OL_UNITS: 184, DEF_UNITS: 71, YEAR_DEFENSES: 55 } as const;
