// GENERATED FILE: DO NOT EDIT.
// Generated by tools/extract/extract-legacy.ts from legacy/beat-the-beasts.jsx
// legacy SHA-256: 94288df62b61768af23eb8be7ad90a86deb6b99ca0a8b234be63b655e827f383
// Colors and names (C legacy line 163, POS_HEX legacy line 181, DECADE_HEX legacy line 197, SKIN_TONES legacy line 214, TEAM_COLORS legacy line 6715, TEAM_NICKS legacy line 6736).
/* eslint-disable */

import type { DecadeHex, Palette, PosHex, SkinTone, TeamColor } from './types.ts';

export const C: Palette = {
  bg: "#08070f",
  surface: "#120f1f",
  surfaceHi: "#1c1733",
  surfaceLo: "#06050c",
  border: "#2a2348",
  borderHi: "#43388a",
  text: "#f4f0ff",
  textMuted: "#9b93c4",
  textDim: "#5f5887",
  emerald: "#aaff00",
  emeraldDim: "#7ecc00",
  gold: "#ffd400",
  sky: "#00e5ff",
  field: "#0a1418",
  fieldStripe: "#0d1a1f",
};

export const POS_HEX: Readonly<Record<string, PosHex>> = {
  QB: { bg: "rgba(255,212,0,0.14)", text: "#ffe14d", solid: "#ffd400", border: "rgba(255,212,0,0.45)" },
  RB: { bg: "rgba(255,42,109,0.14)", text: "#ff5c8a", solid: "#ff2a6d", border: "rgba(255,42,109,0.45)" },
  WR: { bg: "rgba(0,229,255,0.14)", text: "#5cf0ff", solid: "#00e5ff", border: "rgba(0,229,255,0.45)" },
  TE: { bg: "rgba(189,107,255,0.14)", text: "#cf95ff", solid: "#bd6bff", border: "rgba(189,107,255,0.45)" },
  OL: { bg: "rgba(255,138,0,0.14)", text: "#ffac4d", solid: "#ff8a00", border: "rgba(255,138,0,0.45)" },
  DEF: { bg: "rgba(170,255,0,0.14)", text: "#c2ff4d", solid: "#aaff00", border: "rgba(170,255,0,0.45)" },
  DE: { bg: "rgba(255,42,109,0.14)", text: "#ff5c8a", solid: "#ff2a6d", border: "rgba(255,42,109,0.48)" },
  DT: { bg: "rgba(255,138,0,0.14)", text: "#ffac4d", solid: "#ff8a00", border: "rgba(255,138,0,0.48)" },
  LB: { bg: "rgba(170,255,0,0.14)", text: "#c2ff4d", solid: "#aaff00", border: "rgba(170,255,0,0.48)" },
  CB: { bg: "rgba(0,229,255,0.14)", text: "#5cf0ff", solid: "#00e5ff", border: "rgba(0,229,255,0.48)" },
  S: { bg: "rgba(189,107,255,0.14)", text: "#cf95ff", solid: "#bd6bff", border: "rgba(189,107,255,0.48)" },
  DB: { bg: "rgba(0,229,255,0.14)", text: "#5cf0ff", solid: "#00e5ff", border: "rgba(0,229,255,0.48)" },
};

export const DECADE_HEX: Readonly<Record<string, DecadeHex>> = {
  "1960s": { bg: "rgba(255,212,0,0.16)", text: "#ffe14d", border: "rgba(255,212,0,0.42)" },
  "1970s": { bg: "rgba(255,138,0,0.16)", text: "#ffac4d", border: "rgba(255,138,0,0.42)" },
  "1980s": { bg: "rgba(255,42,109,0.16)", text: "#ff5c8a", border: "rgba(255,42,109,0.42)" },
  "1990s": { bg: "rgba(189,107,255,0.16)", text: "#cf95ff", border: "rgba(189,107,255,0.42)" },
  "2000s": { bg: "rgba(0,229,255,0.16)", text: "#5cf0ff", border: "rgba(0,229,255,0.42)" },
  "2010s": { bg: "rgba(0,255,179,0.16)", text: "#4dffc4", border: "rgba(0,255,179,0.42)" },
  "2020s": { bg: "rgba(170,255,0,0.16)", text: "#c2ff4d", border: "rgba(170,255,0,0.42)" },
};

export const SKIN_TONES: readonly SkinTone[] = [
  { id: 0, label: "Tone 1", hex: "#f2d6bd" },
  { id: 1, label: "Tone 2", hex: "#e0b48f" },
  { id: 2, label: "Tone 3", hex: "#c08552" },
  { id: 3, label: "Tone 4", hex: "#8d5524" },
  { id: 4, label: "Tone 5", hex: "#4b2e1a" },
];

export const TEAM_COLORS: Readonly<Record<string, TeamColor>> = {
  ARI: { j: "#97233f", t: "#ffb612", h: "#97233f" },
  ATL: { j: "#a71930", t: "#000000", h: "#000000" },
  BAL: { j: "#241773", t: "#9e7c0c", h: "#241773" },
  BUF: { j: "#00338d", t: "#c60c30", h: "#00338d" },
  CAR: { j: "#0085ca", t: "#101820", h: "#101820" },
  CHI: { j: "#0b162a", t: "#c83803", h: "#0b162a" },
  CIN: { j: "#fb4f14", t: "#000000", h: "#000000" },
  CLE: { j: "#311d00", t: "#ff3c00", h: "#ff3c00" },
  DAL: { j: "#003594", t: "#869397", h: "#003594" },
  DEN: { j: "#fb4f14", t: "#002244", h: "#002244" },
  DET: { j: "#0076b6", t: "#b0b7bc", h: "#0076b6" },
  GB: { j: "#203731", t: "#ffb612", h: "#203731" },
  HOU: { j: "#03202f", t: "#a71930", h: "#03202f" },
  IND: { j: "#002c5f", t: "#ffffff", h: "#002c5f" },
  JAX: { j: "#006778", t: "#d7a22a", h: "#101820" },
  KC: { j: "#e31837", t: "#ffb81c", h: "#e31837" },
  LAC: { j: "#0080c6", t: "#ffc20e", h: "#0080c6" },
  LAR: { j: "#003594", t: "#ffd100", h: "#003594" },
  LV: { j: "#000000", t: "#a5acaf", h: "#000000" },
  MIA: { j: "#008e97", t: "#fc4c02", h: "#008e97" },
  MIN: { j: "#4f2683", t: "#ffc62f", h: "#4f2683" },
  NE: { j: "#002244", t: "#c60c30", h: "#002244" },
  NO: { j: "#101820", t: "#d3bc8d", h: "#d3bc8d" },
  NYG: { j: "#0b2265", t: "#a71930", h: "#0b2265" },
  NYJ: { j: "#125740", t: "#ffffff", h: "#125740" },
  PHI: { j: "#004c54", t: "#a5acaf", h: "#004c54" },
  PIT: { j: "#101820", t: "#ffb612", h: "#101820" },
  SF: { j: "#aa0000", t: "#b3995d", h: "#aa0000" },
  SEA: { j: "#002244", t: "#69be28", h: "#002244" },
  TB: { j: "#d50a0a", t: "#34302b", h: "#34302b" },
  TEN: { j: "#0c2340", t: "#4b92db", h: "#0c2340" },
  WAS: { j: "#5a1414", t: "#ffb612", h: "#5a1414" },
};

export const TEAM_NICKS: Readonly<Record<string, string>> = {
  ARI: "CARDINALS",
  ATL: "FALCONS",
  BAL: "RAVENS",
  BUF: "BILLS",
  CAR: "PANTHERS",
  CHI: "BEARS",
  CIN: "BENGALS",
  CLE: "BROWNS",
  DAL: "COWBOYS",
  DEN: "BRONCOS",
  DET: "LIONS",
  GB: "PACKERS",
  HOU: "TEXANS",
  IND: "COLTS",
  JAX: "JAGUARS",
  KC: "CHIEFS",
  LAC: "CHARGERS",
  LAR: "RAMS",
  LV: "RAIDERS",
  MIA: "DOLPHINS",
  MIN: "VIKINGS",
  NE: "PATRIOTS",
  NO: "SAINTS",
  NYG: "GIANTS",
  NYJ: "JETS",
  PHI: "EAGLES",
  PIT: "STEELERS",
  SF: "49ERS",
  SEA: "SEAHAWKS",
  TB: "BUCS",
  TEN: "TITANS",
  WAS: "COMMANDERS",
};
