// GENERATED FILE: DO NOT EDIT.
// Generated by tools/extract/extract-legacy.ts from legacy/beat-the-beasts.jsx
// legacy SHA-256: 94288df62b61768af23eb8be7ad90a86deb6b99ca0a8b234be63b655e827f383
// Era and scoring tables (ERA_BASE legacy line 4159, DEF_ERA_BASE legacy line 4469, LEAGUE_AVG_PA legacy line 4382, SCORE_K legacy line 4300, REF_ERA legacy line 4167).
/* eslint-disable */

import type { Decade, DefEraBase, EraBase, ScoreK } from './types.ts';

export const ERA_BASE: Readonly<Partial<Record<Decade, EraBase>>> = {
  "1970s": { passY: 155, passTD: 1, rate: 66, int: 1.45, rbY: 62, rbTD: 0.5, recY: 44, recTD: 0.32 },
  "1980s": { passY: 200, passTD: 1.25, rate: 75, int: 1.25, rbY: 64, rbTD: 0.52, recY: 50, recTD: 0.36 },
  "1990s": { passY: 212, passTD: 1.28, rate: 78, int: 1.15, rbY: 60, rbTD: 0.5, recY: 52, recTD: 0.36 },
  "2000s": { passY: 228, passTD: 1.42, rate: 83, int: 1, rbY: 58, rbTD: 0.5, recY: 55, recTD: 0.4 },
  "2010s": { passY: 245, passTD: 1.52, rate: 88, int: 0.85, rbY: 54, rbTD: 0.46, recY: 58, recTD: 0.42 },
  "2020s": { passY: 238, passTD: 1.5, rate: 90, int: 0.8, rbY: 54, rbTD: 0.46, recY: 58, recTD: 0.42 },
};

export const REF_ERA: Decade = "2010s";

export const DEF_ERA_BASE: Readonly<Partial<Record<Decade, DefEraBase>>> = {
  "1960s": { sk: 6, int: 3.5, ff: 1.2, fr: 1.5, imp: 78 },
  "1970s": { sk: 7, int: 3.2, ff: 1.3, fr: 1.6, imp: 78 },
  "1980s": { sk: 7.5, int: 2.8, ff: 1.6, fr: 1.4, imp: 78 },
  "1990s": { sk: 7.5, int: 2.6, ff: 1.8, fr: 1.3, imp: 78 },
  "2000s": { sk: 7, int: 2.4, ff: 1.8, fr: 1.2, imp: 78 },
  "2010s": { sk: 7, int: 2.2, ff: 1.8, fr: 1, imp: 78 },
  "2020s": { sk: 7, int: 2, ff: 1.8, fr: 1, imp: 78 },
};

export const LEAGUE_AVG_PA: Readonly<Record<number, number>> = {
  1970: 17.5,
  1971: 17.5,
  1972: 17,
  1973: 17,
  1974: 17.5,
  1975: 18.5,
  1976: 17,
  1977: 16,
  1978: 18.5,
  1979: 19.5,
  1980: 20.5,
  1981: 21,
  1982: 19,
  1983: 21.5,
  1984: 21,
  1985: 21.5,
  1986: 20.5,
  1987: 20.5,
  1988: 20,
  1989: 20.5,
  1990: 20,
  1991: 19.5,
  1992: 19.5,
  1993: 19.5,
  1994: 20.5,
  1995: 20.5,
  1996: 20.5,
  1997: 20,
  1998: 20.5,
  1999: 20.5,
  2000: 20.5,
  2001: 20.5,
  2002: 21,
  2003: 20.5,
  2004: 21.5,
  2005: 20.5,
  2006: 20.5,
  2007: 21.5,
  2008: 22,
  2009: 21.5,
  2010: 22,
  2011: 22,
  2012: 22.5,
  2013: 23.5,
  2014: 22.5,
  2015: 22.5,
  2016: 22.5,
  2017: 21.5,
  2018: 23.5,
  2019: 22.5,
  2020: 24.5,
  2021: 22.5,
  2022: 21.5,
  2023: 21.5,
  2024: 22,
};

export const SCORE_K: ScoreK = { TD: 7.15, fgC: 3.2, fgY: 0.013, fgTD: 0.55, rate: 0.06, int: 2, sack: 0.35, base: -1.4, pivot: 21, up: 1.7, down: 0.9 };
