// Types for the generated legacy data modules in this folder.
//
// This file is hand-written (the other .ts files here are generated by
// tools/extract/extract-legacy.ts and must not be edited). tsc checks every
// generated value against these interfaces.
//
// Field names are the legacy single-letter names, kept verbatim so the legacy
// engine port reads them exactly as legacy did.

export type Decade = '1960s' | '1970s' | '1980s' | '1990s' | '2000s' | '2010s' | '2020s';
export type OffensePosition = 'QB' | 'RB' | 'WR' | 'TE';
export type DefensePosition = 'DE' | 'DT' | 'LB' | 'CB' | 'S';
/** Draft positions (legacy POSITIONS). */
export type DraftPosition = OffensePosition | 'OL';
/** Roster slots in draft order (legacy SLOT_ORDER). */
export type Slot = 'QB' | 'RB' | 'RB2' | 'WR1' | 'WR2' | 'WR3' | 'TE' | 'TE2' | 'OL';

/**
 * Per-game offensive stat line. Which fields are present depends on position
 * (majority schemas: QB y,t,i,r,ry · RB y,c,r,t · WR y,p,t,c · TE y,t,b); a handful of legacy entries carry another
 * position's schema (see docs/DATA_VALIDATION.md), so every field except the
 * shared `y`/`t` is optional here.
 */
export interface OffenseStats {
  /** QB pass yds/g · RB rush yds/g · WR/TE rec yds/g */
  readonly y: number;
  /** QB pass TD/g · RB/WR/TE TD/g */
  readonly t: number;
  /** QB INT/g */
  readonly i?: number;
  /** QB passer rating · RB rec yds/g */
  readonly r?: number;
  /** QB rush yds/g */
  readonly ry?: number;
  /** RB yds/carry · WR catch % */
  readonly c?: number;
  /** WR yds/target */
  readonly p?: number;
  /** TE block grade */
  readonly b?: number;
}

/** Legacy PLAYERS entry: a player in one team+decade. */
export interface Player {
  /** Stable id `players:<slug>:<team>:<decade>` (frozen in ids.json). */
  readonly id: string;
  /** Index in the legacy PLAYERS array (what legacy `usedIds` holds). */
  readonly legacyIndex: number;
  readonly n: string;
  readonly p: OffensePosition;
  readonly t: string;
  readonly d: Decade;
  readonly s: OffenseStats;
  readonly imp: number;
  /** Era-adjusted rating. Present on every entry, never read by legacy code. */
  readonly ea: number;
}

/** Career (per-decade stint) defensive counting stats. */
export interface DefenseStats {
  readonly sk?: number;
  /** true when sacks are unofficial (pre-1982). */
  readonly u?: boolean;
  readonly int: number;
  readonly ff?: number;
  readonly fr: number;
  readonly td?: number;
  readonly ap: number;
  readonly pb: number;
  readonly dpoy?: number;
}

/** Legacy DEFENSE entry. */
export interface Defender {
  readonly id: string;
  /** Index in the legacy DEFENSE array (legacy Beasts carry it as `idx`). */
  readonly legacyIndex: number;
  readonly n: string;
  readonly p: DefensePosition;
  readonly t: string;
  readonly d: Decade;
  readonly s: DefenseStats;
  readonly imp: number;
}

export interface OLStats {
  /** team rush yds/g */
  readonly ry: number;
  /** sacks allowed/g */
  readonly sa: number;
  /** pass-block grade */
  readonly pb: number;
  /** Pro Bowl linemen */
  readonly pbl: number;
}

/** Legacy UNITS entry with p === 'OL'. */
export interface OLUnit {
  readonly id: string;
  /** Index in the legacy UNITS array (OL and DEF units interleave there). */
  readonly legacyIndex: number;
  readonly n: string;
  readonly p: 'OL';
  readonly t: string;
  readonly d: Decade;
  readonly s: OLStats;
  readonly imp: number;
  /** Key linemen, ' · '-separated. */
  readonly key: string;
}

export interface DefUnitStats {
  readonly pa: number;
  readonly ya: number;
  readonly to: number;
  readonly sk: number;
}

/** Legacy UNITS entry with p === 'DEF'. Never read by legacy code. */
export interface DefUnit {
  readonly id: string;
  readonly legacyIndex: number;
  readonly n: string;
  readonly p: 'DEF';
  readonly t: string;
  readonly d: Decade;
  readonly s: DefUnitStats;
  readonly imp: number;
  readonly key: string;
}

/** [team, points allowed/g, points scored/g] */
export type YearDefenseRow = readonly [string, number, number];

export interface EraBase {
  readonly passY: number;
  readonly passTD: number;
  readonly rate: number;
  readonly int: number;
  readonly rbY: number;
  readonly rbTD: number;
  readonly recY: number;
  readonly recTD: number;
}

export interface DefEraBase {
  readonly sk: number;
  readonly int: number;
  readonly ff: number;
  readonly fr: number;
  readonly imp: number;
}

export interface ScoreK {
  readonly TD: number;
  readonly fgC: number;
  readonly fgY: number;
  readonly fgTD: number;
  readonly rate: number;
  readonly int: number;
  readonly sack: number;
  readonly base: number;
  readonly pivot: number;
  readonly up: number;
  readonly down: number;
}

export interface Palette {
  readonly bg: string;
  readonly surface: string;
  readonly surfaceHi: string;
  readonly surfaceLo: string;
  readonly border: string;
  readonly borderHi: string;
  readonly text: string;
  readonly textMuted: string;
  readonly textDim: string;
  readonly emerald: string;
  readonly emeraldDim: string;
  readonly gold: string;
  readonly sky: string;
  readonly field: string;
  readonly fieldStripe: string;
}

export interface PosHex {
  readonly bg: string;
  readonly text: string;
  readonly solid: string;
  readonly border: string;
}

export interface DecadeHex {
  readonly bg: string;
  readonly text: string;
  readonly border: string;
}

export interface SkinTone {
  readonly id: number;
  readonly label: string;
  readonly hex: string;
}

/** j: jersey, t: trim/number, h: helmet */
export interface TeamColor {
  readonly j: string;
  readonly t: string;
  readonly h: string;
}
